#!/usr/bin/env python3
"""Write _redirects: every .html and trailing-slash spelling of a page, sent to
its clean URL with a 301.

Cloudflare's asset handling already sends /drill-down.html to /drill-down, but
with a 307 -- "temporary" -- which tells a search engine to keep the old
address on file. A 301 says the clean URL is the only one. The canonical tags
already point there; this makes the redirects agree with them.

The rules are listed one per page rather than as a pattern, because a
placeholder in _redirects matches a whole path segment and cannot strip ".html"
from the end of one. Run it again whenever a page is added:

    python3 tools/make_redirects.py
"""
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SKIP = {"404"}                     # served by not_found_handling, never linked


def pages(folder):
    names = sorted(f[:-5] for f in os.listdir(os.path.join(ROOT, folder)) if f.endswith(".html"))
    return [n for n in names if n not in SKIP]


lines = [
    "# Generated by tools/make_redirects.py -- edit that, not this.",
    "/index.html / 301",
    "/demo /demo/ 301",
    "/demo/index.html /demo/ 301",
]
for base, folder in (("/", "."), ("/demo/", "demo")):
    for name in pages(folder):
        if name == "index":
            continue
        clean = base + name
        lines.append(f"{clean}.html {clean} 301")
        lines.append(f"{clean}/ {clean} 301")

with open(os.path.join(ROOT, "_redirects"), "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"_redirects: {len(lines) - 1} rules")
